version: '3.4'
services:
  repository:
    image: symfony-4.0/app
    build: .
    tty: true
    volumes:
      - ./repository:/repository
    networks:
      - overlay

  php:
    image: symfony-4.0/php
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - ./repository:/repository
    networks:
      - overlay

  httpd:
    image: symfony-4.0/httpd
    build: ./docker/httpd
    ports:
      - 8080:80
    volumes:
      - ./repository:/repository
    networks:
      - overlay

networks:
  overlay:
